### ISSUE TITLE
User Interface

### ISSUE THREAD

**Issue by damienstanton** [jdkolassa/Oeuvre#6]
If choice of UI toolkit has not been made, [Semantic-UI](http://semantic-ui.com) would integrate very nicely into this project.

They have several WYSIWYG-editor-friendly buttons available and the asset build process can be partially or fully automated using grunt.

**Comment by jdkolassa** [comment]
I was under the impression NW had some UI that came with it. But I could be
wrong. In that case, we'll go with Semantic, since that's the first
suggestion.

**Comment by damienstanton** [comment]
It [appears](https://github.com/nwjs/nw.js/wiki/Native-UI-API-Manual) to have some native GUI stuff builtin _-cool!-_ although not graphics per se.

I think the decision would depend on whether you want to have the same look across platforms, or if you'd prefer to have each platform look as native as possible.

**Comment by jdkolassa** [comment]
Same look. Maybe code in different looks later, but for now I say just use
the same UI. It should be easier to code...right?

**Comment by damienstanton** [comment]
Yeah, very fast prototyping from what I have played with. I'm currently using it with the `
nooitaf:semantic-ui
` Meteor package for a project at work as well as a personal site I should be getting out soon. You can pick [from a pretty huge list of elements](http://semantic-ui.com/elements/icon.html) and assemble as needed.
